extends:
  - stylelint-config-standard
  - stylelint-prettier/recommended
plugins:
  - stylelint-order
rules:
  unit-disallowed-list:
    - 'px'
  declaration-property-value-allowed-list:
    '/color/':
      - "/^var\\(--/"
      - 'transparent'
  order/properties-alphabetical-order: true
